name: flutter_store
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  logger: ^2.2.0
  url_launcher: ^6.2.5
  carousel_slider: ^4.2.1
  flutter_native_splash: ^2.4.0
  curved_navigation_bar: ^1.0.3
  intl: ^0.19.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  dio: ^5.4.0
  sqflite: ^2.2.6
  shared_preferences: ^2.2.2
  path_provider: ^2.0.14
  path: ^1.8.2
  image_picker: ^0.8.4+4
  file_picker: ^5.5.0

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State management
  get: ^4.6.6
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash: 
  color: "#ffffff"
  image: assets/logo/store_logo_sm.jpg
  android_12: 
    image: assets/logo/store_logo_sm.jpg
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets: 
    - assets/image/onboarding/
    - assets/logo/
    - assets/image/banner/
    - assets/image/product/
    - assets/icon/

